version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/Backend/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "Sniphs98"

  - package-ecosystem: "npm"
    directory: "/Frontend/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "Sniphs98"